version: '3.8'
services:
  db:
    image: postgres:alpine
    restart: always
    container_name: books-db
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  
  pgadmin:
    container_name: esdemo_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
    - ./Configs/servers.json:/pgadmin4/servers.json


networks:
  default:
    name: books-network