version: '3.8'
services:
  database:
    image: postgres:alpine
    restart: always
    container_name: books-db
    # volumes:
    #   - ./data/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  
  pgadmin:
    container_name: esdemo_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "secret"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"

networks:
  default:
    name: books-network